# Generated by Django 5.2.17 on 2026-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_Dataset',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='tbl_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('warning', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tbl_Medicine',
            },
        ),
        migrations.CreateModel(
            name='tbl_Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tips', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tbl_Milestone',
                'ordering': ['week'],
            },
        ),
        migrations.CreateModel(
            name='tbl_Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('recommendation', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tbl_Nutrition',
                'ordering': ['name'],
            },
        ),
    ]
