# Generated by Django 5.2.17 on 2026-09-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_tbl_registration_tbl_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Doctor',
        ),
        migrations.DeleteModel(
            name='tbl_registration',
        ),
    ]
