# Generated by Django 5.2.17 on 2026-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_delete_tbl_doctor_delete_tbl_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_nutrition',
            options={},
        ),
        migrations.AddField(
            model_name='tbl_nutrition',
            name='week_end',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='tbl_nutrition',
            name='week_start',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tbl_nutrition',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
