# Generated by Django 5.2.16 on 2026-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='user_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='user_contact',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='user_password',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='contact',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
