# Generated by Django 5.2.17 on 2026-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_rename_user_address_userregistration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_address', models.TextField(blank=True, default='')),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
