# Generated by Django 5.2.17 on 2026-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_registration_delete_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_registration',
            name='role',
            field=models.CharField(default='USER', max_length=20),
        ),
    ]
