# Generated by Django 5.2.17 on 2026-09-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_registration_is_active_tbl_registration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_registration',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
