# Generated by Django 5.2.17 on 2026-09-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_registration_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_registration',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='tbl_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
    ]
