# Generated by Django 5.2.17 on 2026-09-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_registration_delete_userregistration'),
        ('User', '0002_tbl_userprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_PregnancyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('current_week', models.PositiveIntegerField(default=1)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_tracker', to='Guest.tbl_registration')),
            ],
        ),
    ]
