# Generated by Django 5.2.17 on 2026-09-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_registration_is_active_tbl_registration_role'),
        ('User', '0003_tbl_pregnancytracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_pregnancytracker',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='tbl_userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='tbl_userprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Guest.tbl_registration'),
        ),
        migrations.AlterField(
            model_name='tbl_pregnancytracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_records', to='Guest.tbl_registration'),
        ),
        migrations.AlterField(
            model_name='tbl_userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='tbl_pregnancytracker',
            table='tbl_PregnancyTracker',
        ),
        migrations.AlterModelTable(
            name='tbl_userprofile',
            table='tbl_UserProfile',
        ),
        migrations.CreateModel(
            name='tbl_Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('birth_weight', models.FloatField(blank=True, null=True)),
                ('current_weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='Guest.tbl_registration')),
            ],
            options={
                'db_table': 'tbl_Baby',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='tbl_PregnancyWeeklyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_records', to='User.tbl_pregnancytracker')),
            ],
            options={
                'db_table': 'tbl_PregnancyWeeklyRecord',
                'ordering': ['-week', '-recorded_at'],
            },
        ),
    ]
