# Generated by Django 5.2.17 on 2026-09-26 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_tbl_registration_options_and_more'),
        ('User', '0004_alter_tbl_pregnancytracker_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='USER', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to='Guest.tbl_registration')),
            ],
            options={
                'db_table': 'tbl_AIChatMessage',
                'ordering': ['created_at'],
            },
        ),
    ]
