# Generated by Django 5.2.17 on 2026-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_tbl_baby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_appointment',
            name='notes',
        ),
        migrations.AddField(
            model_name='tbl_appointment',
            name='doctor_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
